Do not recomment use of collections.abc.ByteString
PyCQA/flake8-pyi pull request #350
Opened 2023-02-20 22:37 UTC by hauntsaninja

It is highly confusing and its isinstance / issubclass behaviour does not match the documentation of typing.ByteString

See https://github.com/python/cpython/issues/102092

2023-02-20 22:39 UTC, JelleZijlstra commented
Perhaps we should instead lint against any use of `typing.ByteString`.

2023-02-20 22:39 UTC, AlexWaygood commented on tests/imports.pyi
> +from typing import ByteString
Nit: can we move this out of the "BAD IMPORTS" section? (It should probably go on line 46)

2023-02-20 22:40 UTC, AlexWaygood reviewed
Looks good other than my nit, though a short changelog entry might also be in order

2023-02-20 22:43 UTC, hauntsaninja commented
Thanks for the review! Added the changelog entry, let me know if you think it's too hostile :D

2023-02-20 22:47 UTC, AlexWaygood approved these changes
> let me know if you think it's too hostile :D

We're a linter, our entire raison d'être is to shout at people 🔥

2023-02-20 22:48 UTC, JelleZijlstra commented
Let's hold off on this for now, see the CPython issue.

2023-03-09 05:04 UTC, JelleZijlstra commented
What about adding a new code that complains about any usage of ByteString from either typing or collections? That would fit well with the deprecation we're doing at CPython.

2023-06-05 12:30 UTC, AlexWaygood reviewed
How about we expand this so that `collections.abc.ByteString` and `typing.ByteString` are _both_ banned? Neither really make sense as annotations in a post-PEP-688 world, and it'll be good to have type checkers linters warn when users use the deprecated types in annotations (especially since stub authors won't see any of the `DeprecationWarning`s at runtime, since stubs are never executed at runtime!)

2023-06-05 12:30 UTC, AlexWaygood commented
Oh, my review is just saying exactly what @JelleZijlstra said immediately above a few months ago :)

Anyway, we should revive this!

2023-06-07 00:50 UTC, JelleZijlstra requested changes
Per the above, and this way I can clean up my requested reviews.

2023-06-07 06:57 UTC, AlexWaygood commented
@hauntsaninja I'm happy to take this over if you haven't got the time right now :)

2023-06-07 07:08 UTC, hauntsaninja commented
Ah sure, thank you!

2023-06-07 07:08 UTC, closed without merging